/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo Gutierrez Velez
 */

public class frm_Calculadora extends javax.swing.JFrame  {
     
    int Calculate (){
        int result =0;
        switch( OperationTp ){
                case 1: result = fValue + sValue; break;
                case 2: result = fValue - sValue; break;
                case 3: result = fValue * sValue; break;
                case 4: result = fValue / sValue; break;
            }
        fValue = result;
        sValue = 0;
        OperationTp =0;
       return result;
    }
    
    /**
     * Creates new form frm_Calculadora
     */

    public frm_Calculadora() {
        System.out.println( "First value:" + fValue + " Second value:" +sValue + " Operation:"+ OperationTp ); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Operaciones = new javax.swing.JTextField();
        bt_n1 = new javax.swing.JButton();
        bt_n2 = new javax.swing.JButton();
        bt_n3 = new javax.swing.JButton();
        bt_n4 = new javax.swing.JButton();
        bt_n5 = new javax.swing.JButton();
        bt_n6 = new javax.swing.JButton();
        bt_n7 = new javax.swing.JButton();
        bt_n8 = new javax.swing.JButton();
        bt_n9 = new javax.swing.JButton();
        bt_n0 = new javax.swing.JButton();
        bt_fn_C = new javax.swing.JButton();
        bt_Resultado = new javax.swing.JButton();
        bt_Op_Sumar = new javax.swing.JButton();
        bt_Op_Restar = new javax.swing.JButton();
        bt_Op_Multiplicar = new javax.swing.JButton();
        bt_Op_Dividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_Operaciones.setEditable(false);
        tf_Operaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_Operaciones.setToolTipText("");

        bt_n1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n1.setText("1");
        bt_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n2.setText("2");
        bt_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n3.setText("3");
        bt_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n4.setText("4");
        bt_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n5.setText("5");
        bt_n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n6.setText("6");
        bt_n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n7.setText("7");
        bt_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n8.setText("8");
        bt_n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n9.setText("9");
        bt_n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_n0.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_n0.setText("0");
        bt_n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bts_Number_click(evt);
            }
        });

        bt_fn_C.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_fn_C.setText("c");
        bt_fn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fn_CActionPerformed(evt);
            }
        });

        bt_Resultado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_Resultado.setText("=");
        bt_Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Operation(evt);
            }
        });

        bt_Op_Sumar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_Op_Sumar.setText("+");
        bt_Op_Sumar.setToolTipText("");
        bt_Op_Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Operation(evt);
            }
        });

        bt_Op_Restar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_Op_Restar.setText("-");
        bt_Op_Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Operation(evt);
            }
        });

        bt_Op_Multiplicar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_Op_Multiplicar.setText("*");
        bt_Op_Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Operation(evt);
            }
        });

        bt_Op_Dividir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_Op_Dividir.setText("/");
        bt_Op_Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Operation(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Op_Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_fn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Op_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Op_Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_Operaciones, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_Op_Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tf_Operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Op_Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Op_Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Op_Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_fn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Op_Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void bt_fn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fn_CActionPerformed
        OperationTp=0;
        fValue =0;
        sValue =0;
        tf_Operaciones.setText("");    }//GEN-LAST:event_bt_fn_CActionPerformed

    private void bts_Number_click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bts_Number_click
       boolean isNumeric = (tf_Operaciones.getText() != null && tf_Operaciones.getText().matches("[0-9]+"));
       
       if(isNumeric) tf_Operaciones.setText( tf_Operaciones.getText() + String.valueOf(evt.getActionCommand() ) );
       else tf_Operaciones.setText( String.valueOf(evt.getActionCommand() ) );
       
       if(OperationTp>0){ 
           sValue = Integer.parseInt ( tf_Operaciones.getText()); 
           System.out.println(sValue);
       }
       else { 
           fValue = Integer.parseInt(tf_Operaciones.getText());
           System.out.println(fValue);
       }
    }//GEN-LAST:event_bts_Number_click

    private void btn_Operation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Operation
        if( fValue > 0){
            tf_Operaciones.setText(String.valueOf(evt.getActionCommand()) );
            switch(String.valueOf(evt.getActionCommand())){
                case "+": OperationTp = 1; 
                     System.out.println("sumar"); 
                     break;
                case "-": 
                    OperationTp = 2; 
                    System.out.println("restar");
                    break;
                case "*": 
                    OperationTp = 3; 
                    System.out.println("multiplicar");
                    break;
                case "/": 
                    OperationTp = 4; 
                    System.out.println("dividir");
                    break;
                case "=": 
                    tf_Operaciones.setText( String.valueOf( Calculate()) );
                    break;                
            }
           }        
    }//GEN-LAST:event_btn_Operation

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Calculadora().setVisible(true);
                
            }
        });
    }
 int OperationTp = 0;
 int fValue =0;
 int sValue = 0;      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Op_Dividir;
    private javax.swing.JButton bt_Op_Multiplicar;
    private javax.swing.JButton bt_Op_Restar;
    private javax.swing.JButton bt_Op_Sumar;
    private javax.swing.JButton bt_Resultado;
    private javax.swing.JButton bt_fn_C;
    private javax.swing.JButton bt_n0;
    private javax.swing.JButton bt_n1;
    private javax.swing.JButton bt_n2;
    private javax.swing.JButton bt_n3;
    private javax.swing.JButton bt_n4;
    private javax.swing.JButton bt_n5;
    private javax.swing.JButton bt_n6;
    private javax.swing.JButton bt_n7;
    private javax.swing.JButton bt_n8;
    private javax.swing.JButton bt_n9;
    private javax.swing.JTextField tf_Operaciones;
    // End of variables declaration//GEN-END:variables
}
